# Streamlit Secrets Configuration Template
# This app uses Replit's environment secrets for security
# All credentials are managed through environment variables

# Note: In production, you would add actual values here like:
# [snowflake]
# user = "your_username"
# password = "your_password"
# account = "your_account"
# warehouse = "COMPUTE_WH"
# database = "your_database"
# schema = "your_schema"

# [gemini]
# api_key = "your_gemini_api_key"

# For this Replit deployment, credentials are securely stored in:
# - SF_USER (Snowflake username)
# - SF_PASS (Snowflake password)
# - SF_ACCOUNT (Snowflake account)
# - SF_DB (Snowflake database)
# - SF_SCHEMA (Snowflake schema)
# - GEMINI_API_KEY (Gemini AI API key)
